<?php

return [

    'P1' => 'APPLICATION DOMAIN and CONSENT',
        'P1.1' => 'Personal data of physical persons-users of service of rigmanager.com.ua is processed by LLC "РИГМЕНЕДЖЕР УКРИНА", registered on the legislation of Ukraine, located by address: street Mury 7, Poltava, Ukraine, 36022 (further - Company). A Company is a proprietor and manager of Database of the personal data of users of rigmanager.com.ua.',
        'P1.2' => 'Personal data of users of rigmanager.com.ua is processed on the protected servers located as within the limits of Ukraine.',
        'P1.3' => 'This privacy Policy describes the order of processing of the personal data collected by means of Web-site of www.rigmanager.com.ua (further - Web-site), and the related to it services and instruments, allowing to the users to register oneself on Web-site, publish or look over the already published announcements in real-time. In all mentioned cases Company processes the personal data of users exceptionally within the requirements of Law of Ukraine "About the protection of the personal data" and Convention about defence of persons in connection with the automated processing of the personal data. This privacy Policy is worked out in accordance with the provisions of these documents.',
        'P1.4' => 'By using the Site, the User gives his consent to the Company to process his personal data, such as username, email address, contact phone number, other contact information at the request of the user; ip-addresses, other communication data of users; messages, letters, statements transmitted to the user by other users and vice versa, and also gives his consent to the transfer of his personal data to third parties, including the transfer of personal data abroad, to any third country, in accordance with this Privacy Policy and with the User agreement of services rigmanager.com.ua.',
        'P1.5' => 'Users must know that by following some external links placed on Web-site, they can be redirected to the web-sites (to the applications etc.) of other companies outside hosting space of Company, where information about Users gathers beyond direct control of Company. At that rate Privacy Policy of web-sites and/or applications of the third parties will regulate the order of treatment of the information got from users by these third parties.',
    'P2' => 'INFORMATION COLLECTS, GETS AND PLACES COMPANY',
        'P2.1' => 'Information about a user account: At creation by User of user account on Web-site, Company can demand certain information, such as an actual e-mail address and password. A user account includes such information about user, user name, telephone number and concomitant information, including photos that they can load in the user account. (A user account allows to the users to contact with each other, to express the personal interest in the suggestions). Users bear responsibility for all information placed by them in public posts. An user must attentively consider all risks, related to that he does certain information (in particular, address of e-mail and contact telephone number) public. If an user decided to enter on a Web-site, using service of authentification of other service, for example information from Facebook, Company can get an additional profile, or other information, access to that is given by such third party.',
        'P2.2' => 'Posts and Transactions: Within the activity of the Web-site, Company can place information, including the personal and contact info, necessary for the feasance of transactions between a customer and salesman, for the dispatch of reports and communication between users, and feasances of payments. All information necessary for the psot publication is required at creation of user account. Users bear responsibility for all information placed by them on a Web-site. An user must attentively consider all risks, related to that he does certain information (in particular, personal information) public.',
        'P2.3' => 'Customer service: At the appeal of Users in the department of Customer service, Company can - within the activity of the Web-site - collect the personal information necessary for implementation of User request and feed-back if necessary. A Company can also contact User, using the existent contact information on user account, given for this purpose. A Company can also collect other information about Users communication, for example, any request to Customer service given by Users, or any feed-back given by them. We can process reviews as data, relatively to User - author of review, and User in regard to who a review was left.',
        'P2.4' => 'Information accessible from a social networks user account: Registering oneself on Web-site, or carrying out an entrance on a Web-site by means of services of authentification of social networks, User gives Companies consent to collection and information processing accessible from corresponding user account in social networks, and also on a publication in the corresponding social networks of information about operating of User on Web-site.

        Information that Company does not collect and does not process:

        A Company does not collect and does not process the personal data about a racial or ethnic origin, political, religious or world view persuasions, membership in political parties and trade unions, and similar information.',
    'P3' => 'IP-ADDRESS, COOKIES AND MOBILE IDENTIFIERS',
        'P3.1' => 'Within the activity of the Web-site, Company can collect certain information by means of such technologies as cookies, and local depository (as in Your browser).',
        'P3.2' => 'COOKIES are small text files, that keep information directly on the computer of user, his mobile telephone or other device.',
        'P3.3' => 'By means of cookies, a web server can save, for example preferences and tuning on the User computer, his mobile telephone or other device that after is automatically restored at a next visit. Or, speaking differently, the files of cookies serve, besides other, to do the usage of Web-site more comfortable, thus, for example, that User did not have to repeat the process of Sign in the system at a next visit. A Company uses both permanent and session to the cookie. Permanent cookie remain on the User computer during more protracted period of time, and session to the cookie automatically retire at closing of window of browser.',
        'P3.4' => 'A Company can allow to the third parties, such as advertisement and/or analytical service providers, to collect information, using these types of technologies directly on the web page of Web-site. Data that they collect are guarded according to the Privacy Policy of these third parties.',
    'P4' => 'USE OF THE PERSONAL DATA',
        'P4.1' => 'For providing the services Company can use information that Company collects and places for next purposes:',
            'P4.1.1' => 'providing of Customer service, including for creation and management by the registration users accounts, solving of technical difficulties and access to the different functions;',
            'P4.1.2' => 'adaptation of suggestions and experience, including advertisements on the services or services of the third parties;',
            'P4.1.3' => 'control of general and individual activity of Users, such as a search on keywords, activity on the publications of posts and conclusions of transactions, and also for a management by a traffic on Web-site;',
            'P4.1.4' => 'communication with our users, including service questions, Customer service or settled marketing communications through any accessible communication channels;',
            'P4.1.5' => 'realization of research and analytical activity with the purpose of improvement of our service;',
            'P4.1.6' => 'providing of observance of the User agreement of services of rigmanager.com.ua, including a fight against a swindle and insults;',
        'P4.2' => 'A Company will keep your personal data so long, as far as it is necessary for the achievement of purposes they are collected, including realization of any legal, book-keeping, logging or reporting requirements.

        For determination of storage period Company takes into account a volume, character and sensitiveness of the personal data, potential risk of damnification from the unauthorized use or disclosure of your personal data, purposes because of which Company processes your personal data, and also we whether Company can attain these purposes by means of other facilities, and corresponding legal requirements.

        If in your user account there was not activity more than 24 months, we reserve a right to delete your user account, including all personal data kept in it, that means that you will be no longer able to get access to it and to use it.

        In case of any questions concerning the of data storage period, please, contact with us through the function of "LINK".',
    'P5' => 'INFORMATION EXCHANGE',
        'P5.1' => 'A Company can exchange information that it collects, with affiliated persons (companies operating on the basis of common property or under general control of Naspers Group), located in some third country. These companies can only process and use the obtained personal data in the purposes indicated in p.4 of this Privacy Policy. Thus the passed data remain the subject of this Privacy Policy.',
        'P5.2' => 'A Company does not give the personal information of users to the not affiliated persons.',
        'P5.3' => 'A Company reserves a right to share information with private persons and public authorities in accordance with the requirements of legislation for implementation of:

        fight against a swindle and abuses on Web-site;
        investigations of the supposed breaches of law or fight against any other supposed violations of the User agreement of services of rigmanager.com.ua by Users.',
        'P5.4' => 'A Company can give the personal data of users upon requests to the competent authorities executed in accordance with the requirements of legislation, including in obedience to the clause 93 of Criminal judicial codes of Ukraine.',
        'P5.5' => 'In accordance with Privacy Policy, Company is obligated not to pass in a lease or sell any personal data of User. In case if business of Company or part of this business will be sold or reorganized, and Company passes everything, or practically all assets to the new proprietor, then the personal data of users can be passed to the customer, to provide continuity of maintenance of Web-site.',
        'P5.6' => 'A Company can pass information that it collects, to the third parties that give services of Company, with the purpose of realization of researches, or the grants of services to Users, besides, information been given, remains the subject of this Privacy Policy, and the third parties have no authority to use obtained information differently, than for the grant of services to Company.',
        'P5.7' => 'In the cases of exchange of the personal data envisaged by p.5 of this Privacy Policy, informing of User about exchange of his personal data remains at discretion of Company.',
    'P6' => 'USER CONTROL',
        'P6.1' => 'Access, Edition and Deleting: Users that created a user account, or placed post on Web-site, can get access, edit or delete information that they give. An user bears responsibility for exactness of the given data, or reports on Web-site. If the user account of User was created through the provider of authentication (for example, Facebook Connect), User can also disconnect, or change data of user account through tuning of provider of authentication (for example, on facebook.com). Published information can be edited or deleted in the user profile "LINK" page of Web-site. A Company can stop processing of the personal data of User in case of receipt of writing notification of User about the review of consent to processing of the personal data.',
        'P6.2' => 'Cookies: Most computers and mobile web-browsers (for example, Safari, Firefox, Internet Explorer, Chrome, Opera) provide ingredients managements that allow to the user to limit or block setting of Cookies on your systems. Pay attention, that disabling of Cookies in regard to the domens of the first category (visited web-sites) and other domens (web-sites related to visited) can result on occasion in a limit functionality of these web sites.',
        'P6.3' => 'Other rights of Users due to their personal data processing by Company:',
            'P6.3.1' => 'know about the location of database of the personal data, containing the personal data of users of rigmanager.com.ua, setting and name, location of proprietor and managers of the personal data or to give a commission about the receiving of this information to the authorized agent of Web-site, except the cases set by a law;',
            'P6.3.2' => 'get information about the terms of granting the access to the personal data, including information about the third parties that the personal data of users of Web-site are passed to;',
            'P6.3.3' => 'access to the personal data;',
            'P6.3.4' => 'get answer, whether his personal data are processed, and also to get content of such personal data not later that thirty calendar days from the day of request, except cases described by law;',
            'P6.3.5' => 'to produce the motivated requirement to the proprietor of the personal data with objection against processing of the personal data;',
            'P6.3.6' => 'produce the motivated requirement about a change or elimination of the personal data a proprietor and / or by the manager of the personal data, if these data are processed illegally or are unreliable;',
            'P6.3.7' => 'protection of the personal data from illegal treatment and casual loss, elimination, damage in connection with an intentional concealment, and also on protecting from the information, that are unreliable or defaming honour, dignity and business reputation;',
            'P6.3.8' => 'apply with complaints about processing of the personal data in public and public servants authorities, providing of protection of the personal data is included in plenary powers of that, or in a court;',
            'P6.3.9' => 'apply facilities of legal defense in case of violation of legislation about the protection of the personal data;',
            'P6.3.10' => 'recall a consent to processing of the personal data;',
            'P6.3.11' => 'know the mechanism of the automatic processing of the personal data;',
            'P6.3.12' => 'on protecting from the automated decision having law consequences for the users of Web-site.',
    'P7' => 'SAFETY',
        'P7.1' => 'All information that we collect within resonable limits protected by technical equipments and procedures of providing of safety for prevention of unauthorized division or the use of data. Affiliated with Company persons, reliable partners and other service providers, are obligated to use obtained information from Company in accordance with our safety requirements and this Privacy Policy.',
    'P8' => 'MAKING ALTERATION TO THIS POLITICS',
        'P8.1' => 'This privacy policy was last time renewed on 17.09.2020. A Company can renew this Privacy Policy from time to time, the new release of privacy Policy inures from the moment of her placing in a network the Internet to address indicated in this paragraph, if another is not envisaged by the new release of Privacy Policy. An operating release of privacy Policy always is on a page to address of https://rigmanager.com.ua/privacy.',
        'P8.2' => 'In case if any changes were brought in privacy Policy by Company, with that User does not agree, he is under an obligation to stop the use of services of Web-site. A fact of continuation of the use of Web-site is confirmation of consent and acceptance by User of corresponding release of privacy Policy.',

];
